version: '3.8'

services:

  mtp:
    build: ./mtp
    ports:
      - "4990:5000"

  graphwalker:
    image: altwalker/graphwalker:latest
    ports:
      - "8887:8887"
    command: gw online -s RESTFUL
