services:

  mtp:
    image: mtp
    container_name: planner
    ports:
      - "8000:8000"
    environment:
      - BOOTSTRAP_SERVER=192.168.0.71  # Passing localhost IP as an environment variable

  graphwalker:
    image: altwalker/graphwalker:latest
    container_name: graphwalker
    ports:
      - "8887:8887"
    command: gw online -s RESTFUL
