# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM python:3.7.9-alpine3.13 AS builder

WORKDIR /alfa

COPY requirements.txt /alfa
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /alfa

CMD ["python", "alfa.py"]